<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;

/**
 * FriendshipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FriendshipRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param User $user
     * @param User $friend
     * @return array
     */
    public function findActiveFromFriend(User $user, User $friend)
    {
        $qb = $this->createQueryBuilder('f')
            ->andWhere('f.sender = :friend AND f.receiver = :user')
            ->orWhere('f.sender = :user AND f.receiver = :friend')
            ->setParameter('user', $user)
            ->setParameter('friend', $friend)
        ;

        return $qb->getQuery()->getSingleResult();
    }
}
