<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IngredientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredientRepository extends EntityRepository
{
    /**
     * @param $pattern
     * @return array
     */
    public function searchByPattern($pattern)
    {
        $qb = $this->createQueryBuilder('i')
            ->where('i.name LIKE :pattern')
            ->setParameter('pattern', '%'.$pattern.'%')
        ;

        return $qb->getQuery()->getArrayResult();
    }
}
