<?php

namespace AppBundle\Repository;

/**
 * ShoppingListRecipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShoppingListRecipeRepository extends \Doctrine\ORM\EntityRepository
{
}
